version: 0.2

phases:
  install:
    commands:
      - npm install --production
  build:
    commands:
      - npm run build
artifacts:
  files:
    - build/**/*
    - public/**/*
    - package.json
    - .ebextensions/**/*
    - .env.production